dist: bionic
env:
    global:
    -   GIT_NAME: Dead-Hosts
    -   GIT_EMAIL: dead-hosts@outlook.com
    -   GIT_BRANCH: master
    -   secure: E8qa9gAMsd0SOtBd7HueMljueLy9Zdh0rff47FaO1WHSwrGNHdDZfwnfk42wldCw80BkJYw7qSJCPMY6eOMqa2HK1oAYpNT0HxEF7Eno8woOOM3/UUvgS6N+FvDOpBHeno8zsJh947gH40kzNx6ZD7B3d26JUx8QlzGOBD7ttqfD4rBElw7tsJ9lv9GviXbq055cGyrDSxUZo5n1wA99SWagDjGvcr530n0OtTwPmgBct2dlcTgqk3+joRHYDCDbS4XFM+rKrGXC4DOtrm3mtt57au8Cbsw6eK+aejVKrSWgeKNUrKMG9lzAMwKQLgvk+Q8Db9U+EK8T/l4ZuTB4RhVZroxXk2ehSc3bfTcFlS9shCyXmnAsgmKlVHqAavBF2FI78cackS2EmoV910vLNtmlTISDi5yZAeRv0xfNsEel5wbo8FAynXl6aZQk140Zghnqp42jeOmDh9x0t9l8UOnF4BrILOksUn3YnL7+c12CzPJK+aXlxsMo1iGqgKK+V9PBdqSuB05JnOmFlTPUr+l90pfhqXYOTSfxR28LM6N9h/+/wD20dTm78bhwIi47p28sFDT4DMNbQ9x+6PU3Jq030w6h0G3YYpajs143427eGwUcZj0TuaXxZgZn1oHWGnaJYe4vYD6GYtVA8vXsPWtvtc3qdje5jN63Bv8XmtY=
    -   PYTHON_VERSION: 3.7.5
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- source activate launcher-environment
- python -VV
- pip --version
- pip install --upgrade dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: change
        recipients:
        - dead-hosts@outlook.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
